version: '3.2'

services:

  ###### KAFKA ######

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"

  kafdrop:
    image: obsidiandynamics/kafdrop
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - SERVER_SERVLET_CONTEXTPATH=/
    ports:
      - "9000:9000"
    depends_on:
      - kafka

#  akhq:
#    image: tchiotludo/akhq
#    environment:
#      AKHQ_CONFIGURATION: |
#        akhq:
#          connections:
#            kafka-cluster:
#              properties:
#                bootstrap.servers: "kafka:9092"
#    ports:
#      - "8081:8080"
#    depends_on:
#      - kafka
