server:
port: 8070

spring:
  application:
    name: ms-api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: user-management
          uri: lb://MS-USER-MANAGEMENT
          predicates:
            - Path=/ecommerce-user/v1/**

ecommerce:
  serviceRegistry:
    username: serviceregistry
    password: 'ecommerce123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ecommerce.serviceRegistry.username}:${ecommerce.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost


logging:
  level:
    service-registry: TRACE
    root: debug