spring:
  application:
    name: ms-shopping-cart
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ecommerce-config-server
      username: configServer
      password: 'ecommerce123cs'

logging:
  level:
    dev.ecommerce: TRACE
    root: INFO
    org.springframework.cache: INFO
    org.springframework.web: TRACE
    org.hibernate: INFO