spring:
  application:
    name: ms-user-management
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ecommerce-config-server
      username: configServer
      password: 'ecommerce123cs'

logging:
  level:
    dev.msusermanagement: TRACE
    root: INFO
    org.springframework.cache: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO