spring:
  application:
    name: ms-user-management
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ecommerce-config-server
      username: configServer
      password: 'ecommerce123cs'